### PR TITLE
Fix #25: Add Chrome testing in CI.

### LINKED ISSUE #25: Find a way to test Chrome in CI.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @sjrd

**Comment by sjrd** [comment]
LGTM

**Comment by nicolasstucki** [comment]
@sjrd this is the first commit that should be merged. The other ones should be rebased and retested to test on chrome.

**Comment by sjrd** [comment]
Re-LGTM

**Pull request merged**
