### PR TITLE
Upgrade Deps

### PR DESCRIPTION
**Pull request by godenji**

### CODE REVIEW

**Comment by godenji** [comment]
Build was failing on old Scala versions (that were upgraded to the latest in this PR), but was missing necessary changes to `.travis.yml`.

**Comment by godenji** [comment]
@nicolasstucki @sjrd this PR could use a review.

Build currently fails with:
> This job ran on our Precise, sudo: required environment which was updated on May 4th. Please check [our blog](https://blog.travis-ci.com/2017-05-04-precise-image-updates) for more details about this update.

Assume maintainers have required permissions to kick off the build.

**Comment by sjrd** [comment]
Yeah I guess we first need to fix the build on master. I'm afraid I don't have the time to look into this this week. Hopefully next week I'll get the chance.

**Comment by nicolasstucki** [comment]
Try adding 
```yml
before_script:
  - sudo chmod +x /usr/local/bin/sbt
```

**Comment by sjrd** [comment]
@nicolasstucki Seems to help indeed #66, but not even to fix the build. The errors change though (something Firefox apparently).

**Comment by godenji** [comment]
Yeah, looks like still having permissions issues, not sure what that's about.

Just want to get the ball rolling with upgrading to latest Selenium/Firefox/Chrome -- hopefully one of you has time in the next week or so to sort out what's happening with Travis.

Thanks

**Comment by gzm0** [comment]
Superseded by #69.

**Comment by godenji** [comment]
@gzm0 awesome, thanks getting the repo up-to-date

**Pull request closed without merging**
