### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Review by sjrd — CHANGES_REQUESTED** [review]
We typically have been requesting `openjdk8` instead of not requesting anything. This is safer if Travis decides to change the default.

**Comment by gzm0** [comment]
> This is safer if Travis decides to change the default.

Yes, but its flakier if Travis drops support. I'll change it to `openjdk8` if you want me to, but I'm not sure the JDK matters more than having builds that work :-/

**Comment by sjrd** [comment]
I think it matters, because it is also a promise for
* us that we can build it from JDK8 and publish it from JDK8
* users that they can use this from JDK8, which is still the most-officially supported version for Scala development.

**Comment by gzm0** [comment]
Seems like we have a genuine failure on chrome :-/ We can either:
- Drop it from the CI
- Investigate
- Do some test exclusion hacking like in phantom

**Comment by sjrd** [comment]
Entirely dropping Chrome sounds too harsh.

I suggest we use a test exclusion to repair the build, and that we file an issue to investigate it later.

**Review by sjrd — CHANGES_REQUESTED** [review]
The first commit has a typo. It says 7 instead of 8. Otherwise LGTM.

**Review by sjrd — APPROVED** [review]

**Pull request merged**
