### PR TITLE
Fix #70: Make send/receive interface thread safe

### LINKED ISSUE #70: Make thread safe
This is required for scala-js/scala-js#3040.

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
I manually tested that this works with scala-js/scala-js#3040 (with test in this repo). Still running the Scala.js test suite with the Selenium env (and scala-js/scala-js#3040).

**Comment by gzm0** [comment]
There seem to still be some issues with this on the Scala.js test suite. I suspect that my ad-hoc hacks to make the test suite run trigger an `UndefinedBehaviorError` that kills a VM. This in turn confuses the test runner. N.B. the `RPCCore` gets "JSCom has been closed" when it tries to reply to a message. This is suspicious (since it happens repeatedly). Needs more investigation.

**Comment by sjrd** [comment]
Looks good AFAICT.

Is the failure spurious, or is it the manifestation of a deadlock introduced by this PR?

**Comment by gzm0** [comment]
I has also happened before. So I think this PR is fine. But there are serious issues with the other one. I'll comment there.

**Comment by gzm0** [comment]
Example of how this happened before: https://travis-ci.org/scala-js/scala-js-env-selenium/jobs/259095284

**Review by sjrd — APPROVED** [review]

**Pull request merged**
