### PR TITLE
Update README to scope jsEnv to Test

### PR DESCRIPTION
**Pull request by japgolly**

### CODE REVIEW

**Comment by sjrd** [comment]
Some people want it for `run` too. I think we should mention both in this case?

**Comment by japgolly** [comment]
Ah, yes. How about I change it to something like this ?

``` scala
// Apply to the 'run' command
jsEnv := new org.scalajs.jsenv.selenium.SeleniumJSEnv(BROWSER)

// Apply to tests
jsEnv in Test := new org.scalajs.jsenv.selenium.SeleniumJSEnv(BROWSER)
```

**Comment by sjrd** [comment]
Sounds good.

**Comment by japgolly** [comment]
Updated. Please take another look.

**Comment by nicolasstucki** [comment]
LGTM

**Pull request merged**
