### PR TITLE
Fix #39: Fix Google Chrome install.

### LINKED ISSUE #39: Chrome install is broken on Travis
https://travis-ci.org/scala-js/scala-js-env-selenium/jobs/122994735

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by sjrd** [comment]
The build is stuck, waiting for user input.

**Comment by nicolasstucki** [comment]
I know, I added the `-y` but it is not using it. I will try different ways updating it.

**Comment by nicolasstucki** [comment]
@sjrd, this should be re-reviewed. It is based on https://github.com/Polymer/polymer/blob/master/.travis.yml

**Comment by sjrd** [comment]
What is the status of this issue/PR?

**Comment by nicolasstucki** [comment]
Travis was not stable when executing tests on google chrome. I will rebase and test again.

**Comment by sjrd** [comment]
Apparently it doesn't like not finding `/favicon.ico` -_-'
https://travis-ci.org/scala-js/scala-js-env-selenium/jobs/136377871

**Comment by nicolasstucki** [comment]
Missing `/favicon.ico` is a new issue. I will look into it.

**Comment by sjrd** [comment]
There are non-rare timeouts. The 10m of idle time of Travis run out. (i.e., no line printed for 10m)

**Comment by nicolasstucki** [comment]
Same as before. It looks like on chrome tests randomly get stuck. I do not know if it is a race condition that only manifests itself on the Travis Chrome or if the Travis just crashes silently.

**Comment by sjrd** [comment]
OK then I guess I'll publish a new version with the current state of master.

**Comment by nicolasstucki** [comment]
Sounds good. BTW all tests on chrome pass on my machine.

**Pull request closed without merging**
